# Generated by Django 4.2.18 on 2025-02-01 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kullanici', '0002_alter_kullanici_takim'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('TB2', 'TB2'), ('TB3', 'TB3'), ('Akıncı', 'Akıncı'), ('Kızılelma', 'Kızılelma')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Kanat Takımı', 'Kanat Takımı'), ('Gövde Takımı', 'Gövde Takımı'), ('Kuyruk Takımı', 'Kuyruk Takımı'), ('Aviyonik Takımı', 'Aviyonik Takımı'), ('Montaj Takımı', 'Montaj Takımı')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personnel', to='kullanici.team')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Kanat', 'Kanat'), ('Gövde', 'Gövde'), ('Kuyruk', 'Kuyruk'), ('Aviyonik', 'Aviyonik')], max_length=100)),
                ('airplane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='kullanici.airplane')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='kullanici.team')),
            ],
        ),
        migrations.AlterField(
            model_name='kullanici',
            name='takim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kullanici.team'),
        ),
        migrations.DeleteModel(
            name='Takim',
        ),
    ]
