# Generated by Django 4.2.18 on 2025-02-01 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kullanici', '0003_airplane_team_personnel_part_alter_kullanici_takim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='rol',
            field=models.CharField(default='teknik', max_length=100),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kullanici.team'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
