# Generated by Django 4.2.18 on 2025-02-01 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kullanici', '0005_alter_personnel_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='rol',
        ),
        migrations.AlterField(
            model_name='airplane',
            name='name',
            field=models.CharField(choices=[('TB2', 'TB2'), ('TB3', 'TB3'), ('Akıncı', 'Akıncı'), ('Kızılelma', 'Kızılelma')], max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personnel', to='kullanici.team'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personnel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(choices=[('Kanat Takımı', 'Kanat Takımı'), ('Gövde Takımı', 'Gövde Takımı'), ('Kuyruk Takımı', 'Kuyruk Takımı'), ('Aviyonik Takımı', 'Aviyonik Takımı'), ('Montaj Takımı', 'Montaj Takımı')], max_length=100, unique=True),
        ),
    ]
